### ISSUE TITLE
Add Rest Api

### ISSUE THREAD

**Issue by theimo1221** [Hoffmation/Hoffmation-Base#57]
- [x] Create Rest-Service
- [x] Add basic device requests
- [ ] Add basic room requests

**Comment by theimo1221** [comment]
Adding the basic device request, we ran in an error due to circular dependencies of e.g. ioBroker Socket Connection:

````
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property 'io' -> object with constructor 'Manager'
    |     property 'nsps' -> object with constructor 'Object'
    --- property '/' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/response.js:1128:12)
    at ServerResponse.json (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/response.js:260:14)
    at ServerResponse.send (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/response.js:158:21)
    at /home/hoffmation/Hoffmation-Express/node_modules/hoffmation-base/lib/server/services/rest/rest-service.js:18:24
    at Layer.handle [as handle_request] (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/layer.js:95:5)
    at /home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/index.js:341:12)
    at next (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/index.js:323:13)
    at /home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/index.js:341:12)
    at next (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/index.js:275:10)
    at query (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/index.js:323:13)
    at /home/hoffmation/Hoffmation-Express/node_modules/express/lib/router/index.js:284:7
````

So:

- [ ] Implement functions to reduce the resulting JSON of devices

**Comment by theimo1221** [comment]
It is now possible to call all `devices`

For rooms there still was atleast an issue with `Room --> Einstellungen --> Room --> ....`
